FROM registry.access.redhat.com/ubi9-minimal

LABEL org.opencontainers.image.authors="Tony James <tony@redhat.com>"

COPY influxdata.repo /etc/yum.repos.d/

RUN microdnf install -y procps-ng util-linux && \
    microdnf install -y telegraf && \
    microdnf clean all && \
    gpgconf --kill all

USER telegraf

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
