FROM registry.access.redhat.com/ubi9-minimal

LABEL org.opencontainers.image.authors="Tony James <tony@redhat.com>"

COPY influxdb.repo /etc/yum.repos.d/influxdb.repo

RUN microdnf install -y procps-ng shadow-utils util-linux && \
    microdnf install -y influxdb2 influxdb2-cli && \
    microdnf clean all && \
    gpgconf --kill all && \
    chmod 770 /etc/influxdb /var/lib/influxdb && \
    chown influxdb:root /etc/influxdb /var/lib/influxdb

USER influxdb

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 8086
